### ISSUE TITLE
Duvida!

### ISSUE THREAD

**Issue by danielBRTanimacao** [allan516/Site#1]
Olá, ainda pretende finalizar o seu portfolio ele esta ficando muito legal!

Aqui uma recomendação se vc quiser dar um upgrade no portfolio... esse e o canal do Gustavo Guanabara ele tem diversos cursos e um deles e html e css :D

- [Gustavo Guanabara](https://www.youtube.com/@CursoemVideo)

**Comment by allan516** [comment]
> Olá, ainda pretende finalizar o seu portfolio ele esta ficando muito legal!
> 
> Aqui uma recomendação se vc quiser dar um upgrade no portfolio... esse e o canal do Gustavo Guanabara ele tem diversos cursos e um deles e html e css :D
> 
> * [Gustavo Guanabara](https://www.youtube.com/@CursoemVideo)


Tudo bem Daniel? 

pretendo sim, já  estou acompanhando ele há algum tempo, o cara é fera. Também estou fazendo o curso de JS do Otávio Miranda. 

Qualquer dica que tiver não hesite em escrever, valeeu.

**Comment by danielBRTanimacao** [comment]
@allan516 Que legal eu faço o curso de python do Otávio Miranda recomendo muito também kk
